version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: bloquemundo_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres # <-- ESTE ES EL USUARIO REAL
      POSTGRES_PASSWORD: adminpassword # <-- ESTA ES LA CONTRASEÑA REAL
      POSTGRES_DB: bloquemundo_db
    ports:
      - "5433:5432"
    volumes:
      - bloquemundo_data_final:/var/lib/postgresql/data

volumes:
  bloquemundo_data_final:
